### ISSUE TITLE
PHP 8.1 Redis Deprecation  and fatal error

### ISSUE THREAD

**Issue by mavas84** [BoldGrid/w3-total-cache#571]
When using PHP 8.1 issues occur with some deprecated code which may trigger a fatal error.
```
Deprecated: Redis::pconnect(): Passing null to parameter #2 ($port) of type int is deprecated in /web/htdocs/www.sinapsi.org/home/wordpress/wp-content/plugins/w3-total-cache/Cache_Redis.php on line 528

Deprecated: Redis::pconnect(): Passing null to parameter #2 ($port) of type int is deprecated in /web/htdocs/www.sinapsi.org/home/wordpress/wp-content/plugins/w3-total-cache/Cache_Redis.php on line 528
Fatal error: Uncaught TypeError: mysqli_num_fields(): Argument #1 ($result) must be of type mysqli_result, bool given in /web/htdocs/www.sinapsi.org/home/wordpress/wp-includes/wp-db.php:3547 Stack trace: #0 /web/htdocs/www.sinapsi.org/home/wordpress/wp-includes/wp-db.php(3547): mysqli_num_fields() #1 /web/htdocs/www.sinapsi.org/home/wordpress/wp-includes/wp-db.php(737): wpdb->load_col_info() #2 /web/htdocs/www.sinapsi.org/home/wordpress/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php(218): wpdb->__get() #3 /web/htdocs/www.sinapsi.org/home/wordpress/wp-content/plugins/w3-total-cache/DbCache_WpdbNew.php(122): W3TC\DbCache_WpdbInjection_QueryCaching-
A critical error has occurred on your website
```
The error message refers to the 2nd parameter "$port", which is set at https://github.com/W3EDGE/w3-total-cache/blob/2.2.6/Cache_Redis.php#L518 .  The port is an integer returned by https://github.com/W3EDGE/w3-total-cache/blob/ff9c9942b031fb258c372d2322f3a87e2d2ca0ac/Util_Content.php#L100 .
Although, https://github.com/W3EDGE/w3-total-cache/blob/2.2.6/Cache_Redis.php#L518 specifies a default of null for the port.  when the site config uses a server hostname with no port.  Usually, the server is "127.0.0.1:6379".
Line 528  has $this->_read_timeout where the value defaults to integer 0 in https://github.com/W3EDGE/w3-total-cache/blob/2.2.6/ConfigKeys.php#L124-L127
The value is set at https://github.com/W3EDGE/w3-total-cache/blob/2.2.6/Cache_Redis.php#L101

When the  Redis port is set as null, then we may have to update https://github.com/W3EDGE/w3-total-cache/blob/2.2.6/Cache_Redis.php#L518 to not have a second parameter specified. 
Check the default 0 used in https://github.com/W3EDGE/w3-total-cache/blob/ff9c9942b031fb258c372d2322f3a87e2d2ca0ac/Util_Content.php#L100 .
Reference topic: https://wordpress.org/support/topic/wordpress-version-6-0-2-fatal-error-when-php-8-1/
https://wordpress.org/support/topic/redis-issue-on-php-8/

**Comment by mavas84** [comment]
Fixed in https://github.com/W3EDGE/w3-total-cache/pull/574
