### ISSUE TITLE
Guzzle version conflict with authorizor plugin

### ISSUE THREAD

**Issue by use** [BoldGrid/w3-total-cache#676]
Hello, we're using w3c-total-cache, along with https://github.com/uhm-coe/authorizer

We're seeing a problem similar to the one which @figureone previously submitted a patch for:
https://github.com/BoldGrid/w3-total-cache/issues/642

Below is a sample error log. We see this problem happen when attempting to upload media.

```
[Thu Apr 27 17:20:34.911969 2023] [php7:error] [pid 28350] [client 10.30.2.186:16568] PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\\Utils::chooseHandler() in wp-content/plugins/authorizer/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\\choose_handler()
#1 wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\\HandlerStack::create()
#2 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\\Client->__construct()
#3 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\\Handler\\GuzzleV6\\GuzzleHandler->__construct()
#4 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/ClientResolver.php(652): Aws\\default_http_handler()
#5 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Client in wp-content/plugins/authorizer/vendor/guzzlehttp/guzzle/src/functions.php on line 61
```

w3 total cache version: 2.3.1
authorizer version: 3.6.2
wordpress version: 6.2

**Comment by figureone** [comment]
Do you know what the actual error message was? Looks like it got trimmed out at the beginning of your sample error log.

I'm guessing it's because guzzle 6.5.8 is used here in w3-total-cache (probably for php5 compatibility), whereas Authorizer is at 7.5.0 (will be at 7.5.1 shortly with the next release of Authorizer).
https://plugins.trac.wordpress.org/browser/w3-total-cache/trunk/vendor/guzzlehttp/guzzle/CHANGELOG.md
https://github.com/uhm-coe/authorizer/blob/05bcdc6921478154232240fb52a464a34f172cd1/vendor/guzzlehttp/guzzle/CHANGELOG.md

**Comment by use** [comment]
Oops - here is the whole thing - and I'll edit my original comment

```
[Thu Apr 27 17:20:34.911969 2023] [php7:error] [pid 28350] [client 10.30.2.186:16568] PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\\Utils::chooseHandler() in wp-content/plugins/authorizer/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\\choose_handler()
#1 wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\\HandlerStack::create()
#2 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\\Client->__construct()
#3 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\\Handler\\GuzzleV6\\GuzzleHandler->__construct()
#4 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/ClientResolver.php(652): Aws\\default_http_handler()
#5 wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Client in wp-content/plugins/authorizer/vendor/guzzlehttp/guzzle/src/functions.php on line 61

**Comment by cssjoe** [comment]
@use @figureone We have updated the AWS and Guzzle dependencies in our last patch release 2.7.3.  The new Guzzle version is `7.8.1`.  Please let us know if you can still reproduce the issue.

**Comment by figureone** [comment]
Confirming the issue has been resolved. Thanks @cssjoe!
