### ISSUE TITLE
problem with site

### ISSUE THREAD

**Issue by kampol24** [BoldGrid/w3-total-cache#723]
Hello
I tried to use w3 total cache to optimize my website but it failed.
I got error which I don't know how to solve, should I connect to FTP and simply delete w3 cache to solve this?
or what should I do?

error:

Fatal error: Uncaught Error: Call to undefined method W3TC\ObjectCache_WpObjectCache::get_multiple() in /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/object-cache.php:71 Stack trace: #0 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/meta.php(1155): wp_cache_get_multiple(Array, 'term_meta') #1 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/meta.php(645): update_meta_cache('term', Array) #2 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/meta.php(572): get_metadata_raw('term', 20, '_pll_strings_tr...', true) #3 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/taxonomy.php(1383): get_metadata('term', 20, '_pll_strings_tr...', true) #4 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/include/mo.php(52): get_term_meta(20, '_pll_strings_tr...', true) #5 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/include/base.php(127): PLL_MO->import_from_db(Object(PLL_Language)) #6 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/class-wp-hook.php(310): PLL_Base->load_strings_translations('pl') #7 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #8 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #9 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/frontend/choose-lang.php(104): do_action('pll_language_de...', 'pl', Object(PLL_Language)) #10 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/frontend/choose-lang.php(209): PLL_Choose_Lang->set_language(Object(PLL_Language)) #11 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/frontend/choose-lang-url.php(58): PLL_Choose_Lang->home_language() #12 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/frontend/choose-lang-url.php(34): PLL_Choose_Lang_Url->set_language_from_url() #13 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/frontend/frontend.php(118): PLL_Choose_Lang_Url->init() #14 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/plugins/polylang/include/class-polylang.php(263): PLL_Frontend->init() #15 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/class-wp-hook.php(308): Polylang->init('') #16 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #17 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #18 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-settings.php(486): do_action('plugins_loaded') #19 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-config.php(99): require_once('/home/klient.dh...') #20 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-load.php(50): require_once('/home/klient.dh...') #21 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-blog-header.php(13): require_once('/home/klient.dh...') #22 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/index.php(17): require('/home/klient.dh...') #23 {main} thrown in /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/object-cache.php on line 71
W witrynie wystąpił błąd krytyczny.

**Comment by kampol24** [comment]
I connected to FTP, changed name of this plugin folder and site works but I can't connect to admin page

I got error:
W3 Total Cache Error: some files appear to be missing or out of place. Please re-install plugin or remove /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/advanced-cache.php. 

Fatal error: Uncaught Error: Call to undefined function wp_kses() in /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/db.php:28 Stack trace: #0 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-includes/load.php(570): require_once() #1 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-settings.php(124): require_wp_db() #2 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-config.php(99): require_once('/home/klient.dh...') #3 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-load.php(50): require_once('/home/klient.dh...') #4 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-admin/admin.php(34): require_once('/home/klient.dh...') #5 /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-admin/index.php(10): require_once('/home/klient.dh...') #6 {main} thrown in /home/klient.dhosting.pl/kodigo/kampol24.pl/public_html/wp-content/db.php on line 28
W witrynie wystąpił błąd krytyczny.

[Dowiedz się więcej o rozwiązywaniu problemów z WordPressem.](https://wordpress.org/documentation/article/faq-troubleshooting/)
