### ISSUE TITLE
Blank Full Site Editor

### ISSUE THREAD

**Issue by Pulsar-X** [BoldGrid/w3-total-cache#766]
WordPress Version: 6.3.2
W3 Total Cache Version: 2.6.0

When I enter the Full Site Editor, I just get a blank, white page. The Browser console reveals that the server answers with a 500: Internal server Error.

Checking the logs, I get this:
```
[07-Nov-2023 10:58:02 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(310): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3622): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(1300): determine_locale()
#8 /html/wordpress/wp-includes/l10n.php(1331): _load_textdomain_just_in_time('...')
#9 /html/wordpress/wp-includes/l10n.php(185): get_translations_for_domain('...')
#10 /html/wordpress/wp-includes/l10n.php(297): translate('...', '...')
#11 /html/wordpress/wp-content/plugins/w3-total-cache/UsageStatistics_Widget.php(25): __('...', '...')
#12 /html/wordpress/wp-content/plugins/w3-total-cache/UsageStatistics_Plugin_Admin.php(19): W3TC\UsageStatistics_Widget->init()
#13 /html/wordpress/wp-content/plugins/w3-total-cache/Root_Loader.php(140): W3TC\UsageStatistics_Plugin_Admin->run()
#14 /html/wordpress/wp-content/plugins/w3-total-cache/Root_Loader.php(274): W3TC\Root_Loader->run()
#15 /html/wordpress/wp-content/plugins/w3-total-cache/w3-total-cache.php(73): require_once('...')
#16 /html/wordpress/wp-settings.php(407): include_once('...')
#17 /html/wordpress/wp-config.php(131): require_once('...')
#18 /html/wordpress/wp-load.php(50): require_once('...')
#19 /html/wordpress/wp-admin/admin.php(34): require_once('...')
#20 /html/wordpress/wp-admin/site-editor.php(12): require_once('...')
#21 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
[07-Nov-2023 10:58:02 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "SECURE_AUTH_COOKIE" in /html/wordpress/wp-includes/pluggable.php:929
Stack trace:
#0 /html/wordpress/wp-includes/pluggable.php(694): wp_parse_auth_cookie(false, '')
#1 /html/wordpress/wp-includes/class-wp-hook.php(310): wp_validate_auth_cookie(false)
#2 /html/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /html/wordpress/wp-includes/user.php(3622): apply_filters('...', false)
#4 /html/wordpress/wp-includes/pluggable.php(70): _wp_get_current_user()
#5 /html/wordpress/wp-includes/l10n.php(98): wp_get_current_user()
#6 /html/wordpress/wp-includes/l10n.php(152): get_user_locale()
#7 /html/wordpress/wp-includes/l10n.php(894): determine_locale()
#8 /html/wordpress/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#9 [internal function]: WP_Fatal_Error_Handler->handle()
#10 {main}
  thrown in /html/wordpress/wp-includes/pluggable.php on line 929
```

Weirdly, I get this Error when I have both W3 Total Cache and WP Statistics activated, or just either one of them.

I have reported this to WP Statistics too ( https://github.com/wp-statistics/wp-statistics/issues/443 ), but since I also get this error when I just have W3 Total Cache activated, it might just be a coincidence that both Plugins have the same issue.

**Comment by Pulsar-X** [comment]
Hi,
thank you for your response! I am using the free version of W3 Total Cache, so I don't even have the option to enable Usage Statistics in W3 Total Cache.

Maybe there lies the issue? That the plugin tries to load some aspects of the Usage Statistics even though I use the free version and have never enabled statistics?

**Comment by cssjoe** [comment]
@Pulsar-X We resolved the issue in one of our recent patch releases.  If you are still having trouble, then please reopen this issue.  We will be happy to look into it further.
