### ISSUE TITLE
Not working with 5.8

### ISSUE THREAD

**Issue by piotr-sikora-v** [BoldGrid/w3-total-cache#988]
w3-total-cache show as my 5.8 version is supported, but it does not work.
here is error on setup guide.

```
2024/11/07 11:39:42 [error] 1413401#1413401: *9604807 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught W3TC\Util_Environment_Exceptions in /var/www/wordpress/wp-content/plugins/w3-total-cache/PgCache_Environment.php:17
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/w3-total-cache/SetupGuide_Plugin_Admin.php(261): W3TC\PgCache_Environment->fix_on_wpadmin_request()
#1 /var/www/wordpress/wp-includes/class-wp-hook.php(303): W3TC\SetupGuide_Plugin_Admin->config_pgcache()
#2 /var/www/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /var/www/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /var/www/wordpress/wp-admin/admin-ajax.php(187): do_action()
#5 {main}
  thrown in /var/www/wordpress/wp-content/plugins/w3-total-cache/PgCache_Environment.php on line 17" while reading response header from upstream, client: 83.15.130.205, server: wymianaopon.pl, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "wymianaopon.pl", referrer: "https://wymianaopon.pl/wp-admin/admin.php?page=w3tc_setup_guide"
  ```

When I skip it, and set cache object to redis, then it show to works, but nothing is coming to redis (redis configuration on test show pass).

In page debug I only see something like:
```
Object cached 0/0
```

**Comment by cssjoe** [comment]
@piotr-sikora-v We suspect there is an issue with the `Util_Environment_Exceptions.php` loading.  It may be an issue with the hosting environment.  Your website HTML comment shows "Object Caching 203/210 objects using Redis, " meaning that Redis is being utilized.  If you are still seeing errors logged, then please provide more information to help us replicate the issue.
